branch-defaults:
  main:
    environment: null
    group_suffix: null
  test:
    environment: Wikitreedia-env
environment-defaults:
  Wikitreedia-env:
    branch: null
    repository: null
global:
  application_name: Wikitreedia
  default_ec2_keyname: null
  default_platform: Node.js 14 running on 64bit Amazon Linux 2
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli2
  sc: git
  workspace_type: Application
